- name: Stop Gogs service
  systemd:
    name: gogs
    state: stopped

- name: Download specific Gogs binary
  get_url:
    url: "http://{{ gogs_repository }}/repositor/gogs-artifacts/gogs/{{ gogs_version }}/gogs-{{ gogs_version }}"
    dest: "{{ gogs_home }}/gogs-{{ gogs_version }}"
    mode: '0755'
    force: true

- name: Set ownership of Gogs binary
  file:
    path: "{{ gogs_home }}/gogs-{{ gogs_version }}"
    owner: "{{ gogs_user }}"
    group: "{{ gogs_group }}"

- name: Update symlink to new version
  file:
    src: "{{ gogs_home }}/gogs-{{ gogs_version }}"
    dest: "{{ gogs_home }}/gogs"
    state: link

- name: Start Gogs service
  systemd:
    name: gogs
    state: started
    daemon_reload: true

- name: Check if Gogs is running
  uri:
    url: "http://localhost:{{ gogs_server_port }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 6
  delay: 10