---
- name: Install Nginx
  apt:
    name: 
      - nginx
      - nginx-extras
    state: present
    update_cache: yes

- name: Create Nginx configuration
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/sites-available/load-balancer.conf
  notify: Reload Nginx

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/load-balancer.conf
    dest: /etc/nginx/sites-enabled/load-balancer.conf
    state: link
  notify: Reload Nginx

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx