# database: 8000
# build: 8001
# filehost: 8002
# balancer: 8003
# server: 8004, 8005, ....

version: '3'
services:
  database:
    image: ubuntu-sshd-with-sudo:latest
    container_name: database
    ports:
      - "8000:22"
    expose:
      - "5432"
    environment:
      - SSH_USERNAME=databaseSSH
      - PASSWORD=databaseSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  build:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: build
    ports:
      - "8001:22"
    environment:
      - SSH_USERNAME=buildSSH
      - PASSWORD=buildSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  filehost:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: filehost
    ports:
      - "8002:22"
    expose:
      - "139"
      - "445"
    environment:
      - SSH_USERNAME=filehostSSH
      - PASSWORD=filehostSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  balancer:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: balancer
    ports:
      - "8003:22"
      - "80:80"
    environment:
      - SSH_USERNAME=balancerSSH
      - PASSWORD=balancerSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  gogs1:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: gogs1
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_BIND_SERVICE
    ports:
      - "8004:22"
    expose:
      - "3000"
    environment:
      - SSH_USERNAME=gogsSSH
      - PASSWORD=gogsSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  gogs2:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: gogs2
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_BIND_SERVICE
    ports:
      - "8005:22"
    expose:
      - "3000"
    environment:
      - SSH_USERNAME=gogsSSH
      - PASSWORD=gogsSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  gogs3:
    image: ubuntu-sshd-with-sudo:latest 
    container_name: gogs3
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_BIND_SERVICE
    ports:
      - "8006:22"
    expose:
      - "3000"
    environment:
      - SSH_USERNAME=gogsSSH
      - PASSWORD=gogsSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge